config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'

  get "users/check_email" =>"users#check_email"
  get "sessions/email_exist" =>"sessions#email_exist"
  

  post "time_sheets/autosave"=>"time_sheets#autosave"
  post "time_sheets/search_record"=>"time_sheets#search_record"
  resources :users
  resources :sessions
  resources :time_sheets

  root 'users#index'

end

app/models/time_sheet.rb
class TimeSheet < ActiveRecord::Base
	belongs_to :user
	
	validates :project_name, :presence =>true,:length => {:maximum =>30}
	validates :description, :presence =>true
    validates :working_time, :presence =>true
    validates :user_id, :presence =>true
    validates :date, :presence =>true

    def self.saved_minutes(object)
    	saved_minutes = TimeSheet.where(date: object.date).where(user_id: object.user.id).all
    	sum = 0;
    	saved_minutes.each { |u| sum += u.working_time }; 
    	sum
    	@total_minutes = sum + object.working_time;
    end
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password :validations => false
  has_many :time_sheets
	validates :name, :presence =>true,
	:format => {:with => ConfigCenter::GeneralValidations::NAME_FORMAT_REG_EXP},
	:unless => proc{|u| u.provider.present?}


	validates :email, :presence =>true,
	:uniqueness => true,
	:format => {:with => ConfigCenter::GeneralValidations::EMAIL_FORMAT_REG_EXP },:unless => proc{|u| u.provider.present?}


	validates :password, :presence =>true,
	:length => {:minimum => 6 },
	:unless => proc{|u| u.provider.present?}
  
 mount_uploader :image, ImageUploader
def self.authenticate(email, password)
	
    @user = find_by_email(email)
    
    if @user && @user.password_digest == BCrypt::Engine.hash_secret(password, user.password_digest)
    
    @user
    else
    nil
  end
end
 def self.from_omniauth(auth)
   create! do |user|
    user.provider = auth['provider']
    user.uid = auth['uid']
    user.oauth_token = auth['oauth_token']
    if auth['info']
      user.name = auth['info']['name'] || ""
      user.email = auth['info']['email'] || ""
    end
  end
end
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :set_cache_buster  
  helper_method :current_user

  
  private
  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end 

  def disable_nav
    @disable_nav = true
  end

  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
  end

  def require_login
    unless session[:user_id]
     flash[:error] = "You must be logged in to access this section"
     redirect_to root_path 
   end
 end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :set_cache_buster
  def new
    respond_to do |format|
      format.js{}
    end
  end
#hihi
  def create
    if params[:provider] == "linkedin"
      auth = User.from_omniauth(env["omniauth.auth"])
      @user = User.find_by_provider_and_uid(auth["provider"],
        auth["uid"]) || User.create_with_omniauth(auth)
    else
      @user = User.find_by_email(params[:user][:email])
      @user=nil unless @user.authenticate(params[:user][:password])
    end
    if @user
      session[:user_id] = @user.id
      redirect_to time_sheets_path
      flash[:success] = "You have logged in successfullly!"
    else
      flash[:error] = "Invalid email or password"
      redirect_to root_path
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/time_sheets_controller.rb
class TimeSheetsController < ApplicationController
	before_filter :require_login
	before_filter :disable_nav, only: [:search_record]
	
	def index
		@date = Date.today.strftime("%Y-%m-%d")
		@time_sheets = current_user.time_sheets.where(date: @date)
		@time_sheet = TimeSheet.new()
		@total_time = 0
		@time_sheets.each do |entry|
			@total_time += entry.working_time
		end
		@total = time_format(@total_time)

	end

	def new
	end

	def create
		@time_sheets = current_user.time_sheets
		@time_sheet = TimeSheet.new(time_sheet_params)
		@time_sheet.user_id = current_user.id
		@total_minutes = TimeSheet.saved_minutes(@time_sheet)
		if @time_sheet.valid? && @total_minutes < 1440
			@time_sheet.save
			@success = true
			respond_to do |format|
				format.js {}
			end
		else
			@success = false
			render(:index) { |page| page.reload }
			flash[:error] = "Exceeds 24 hours"
			respond_to do |format|
				format.js do
				end
			end

		end
	end

	def edit
		@time_sheet = TimeSheet.find(params[:id])
	end

	def update
		@time_sheet = TimeSheet.find(params[:id])
		if @time_sheet.update(time_sheet_params)
			redirect_to time_sheets_path
		else
			render 'edit'
		end
	end

	def search_record
		@date = params[:date] || Date.today.strftime("%Y-%m-%d")
		@time_sheets = current_user.time_sheets.where(date: params[:date])
		render json: @time_sheets
	end


	def show
		@time_sheet = TimeSheet.find(params[:id])
	end

	private
	def time_sheet_params
		params.require(:time_sheet).permit(:project_name, :description, :working_time, :date)
	end

	def time_format(minutes)
		hours = minutes/60
		minutes = minutes%60
		"#{hours}:#{minutes}"
	end
	
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
	before_filter :require_login
  before_filter :disable_nav, only: [:search_record]
	 before_filter :set_cache_buster  
	def index
		@date = Date.today.strftime("%m/%d/%Y")
		@time_sheets = current_user.time_sheets.where(date: @date)
		@total_time = 0
		@time_sheets.each do |entry|
          @total_time += entry.working_time
          
		end


	end

	def new
		# @time_sheet = TimeSheet.new
		# respond_to do |format|
		# 	format.js{}
		# end
	end

	def create
		@time_sheet = current_user.time_sheets.build(time_sheet_params)
		
		if @time_sheet.valid?

			@time_sheet.save
			@success = true
			respond_to do |format|
				format.html{ redirect_to timesheets_path }
			end
		else
			@success = false
			@time_sheets = current_user.time_sheets
			render 'index'
		end
	end

	def autosave

		@time_sheet = TimeSheet.new(time_sheet_params)

		if @time_sheet.valid?
			@time_sheet.save
			@success = true
			render text: "ok"
		else
			@success = false
			render text: "failure"
		end
	end

	def edit
		@time_sheet = TimeSheet.find(params[:id])
	end


	 def update
    @time_sheet = TimeSheet.find(params[:id])
 
    if @time_sheet.update(time_sheet_params)
      redirect_to timesheets_path
    else
      render 'edit'
    end
  end

	def search_record
      @time_sheets = current_user.time_sheets.where(date: params[:date])
      render json: @time_sheets
	end


	def show
		@time_sheet = TimeSheet.find(params[:id])
	end

	private
	def time_sheet_params
		params.require(:time_sheet).permit(:project_name, :description, :working_time, :date)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :set_cache_buster 
  def index
  end

  def check_email
    @user = User.find_by_email(params[:user][:email])
    respond_to do |format|
      format.json { render :json => !@user  }
    end
  end
   

  def new
    @user = User.new
    respond_to do |format|
      format.js{}
    end
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      @success = true
      session[:user_id] = @user.id
      respond_to do |format|
        format.html{ redirect_to time_sheets_path }
      end
    else
      @success = false
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/timesheet_helper.rb
module TimesheetHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<title>Timesheet</title>
	
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
    
	<%= render 'layouts/common/header' unless @disable_nav %> 

	<div id="div_flash_message" class="container">
		<%= render :partial=>"/layouts/common/flash_messages" -%>
	</div>
	<%= yield %>
	<div id="popup_modal" class="modal fade"></div>
</body>
</html>

app/views/layouts/common/_flash_messages.html.erb
<%
if request.xhr?
	flash_message = flash.now[:success] || flash.now[:notice] || flash.now[:alert] || flash.now[:error]
	style_classes = ""
else
	style_classes = ""
	flash_message = flash[:success] || flash[:notice] || flash[:alert] || flash[:error]
end
cls_name = "alert-info"
cls_name = 'alert-success' if flash.now[:success] || flash[:success]
cls_name = 'alert-warning' if flash.now[:alert] || flash[:alert]
cls_name = 'alert-danger' if flash.now[:error] || flash[:error]

flash_message = flash_message.strip if flash_message

%>

<% unless flash_message.blank? %>
<div id = "flash">
	<div class="<%= style_classes %> alert <%= cls_name %> fade in mb-10" data-alert="alert">
		<a class="close" data-dismiss='alert' href="#">×</a>
		<p><%= flash_message %></p>
	</div>
</div>
<% end %>

app/views/layouts/common/_footer.html.erb
<!--    Footer-->

  <script src="assets/js/jquery.js"></script>
  <script src="assets/js/bootstrap.js"></script>

app/views/layouts/common/_header.html.erb
<!--    Header-->
<nav class="navbar navbar-inverse ">
  <div class="container">
    <div class="navbar-header">
      <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a href="#" class="navbar-brand">Timesheet</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if current_user.present? %>
       <li>
        <%= image_tag  current_user.image,  :alt =>"Image", :class => "img-rounded profile-pic" %>
        </li>
        <li>
          <h3 class="ujwala"><%= current_user.name.titleize %></h3>

        </li>
        <li>

        <%= button_to 'log out', session_path(:id => current_user.id),:method=> :delete, :class => "btn btn-success signup-login-btn", 'data-toggle' => 'modal', 'data-target'=>'#myModal' %>

        </li>
        <% else %>
        <li>
          <%= button_to "Sign up", new_user_path ,:method=> :get, remote: true, :class=>"btn btn-success signup-login-btn", 'data-toggle' => 'modal', 'data-target'=>'#myModal'%>
        </li>
        <li>
          <%= button_to 'log in', new_session_path,:method=> :get, :class => "btn btn-success signup-login-btn", 'data-toggle' => 'modal', 'data-target'=>'#myModal', remote: true %>
        </li>
        <% end %>
      </ul>
    </div><!--/.navbar-collapse -->
  </div>
</nav>

app/views/layouts/common/_signin_modal.html.erb
 <div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">Log In</h4>
    </div>
    <%= form_for :user, url: sessions_path, :method => :post,remote: true, html: {:class =>"form-horizontal", :id => "sign_in"} do |f| %>
    <div class="modal-body">

      <form class="form-horizontal">
        <div class="form-group">
          <label for="inputEmail" class="col-sm-3 control-label">Email id</label>
          <div class="col-sm-7">
            <%= f.text_field :email, :class =>"form-control",:id =>"inputemail", :placeholder => "email" %>
          </div>
          <div class="col-sm-2"></div>
        </div>
        <div class="form-group">
          <label for="inputPassword" class="col-sm-3 control-label">Password</label>
          <div class="col-sm-7">
            <%= f.password_field :password, :class =>"form-control",:id =>"inputPassword",:placeholder => "Password" %>
          </div>
          <div class="col-sm-2"></div>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit "Ok", :class =>"btn btn-primary ok-btn-padding" %>

        <button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
        <center> <%= link_to "Sign in with linkedin", "/auth/linkedin", id: "sign_in" %></center>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/common/_signup_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">Sign Up</h4>
    </div>
    <%= form_for :user, url: users_path, method: "post",authenticity_token: true, remote: true, html: {:class =>"form-horizontal", :id => "sign_up"} do |f| %>
    <div class="modal-body">
      <div class="form-group">
        <label for="Name" class="col-sm-3 control-label">Username*</label>
        <div class="col-sm-7">
         <%= f.text_field :name, :class =>"form-control",:id =>"Name", :placeholder => "Name" %>
       </span>
     </div>
     <div class="col-sm-2"></div>
   </div>
   <div class="form-group">
    <label for="inputEmail" class="col-sm-3 control-label">Email id*</label>
    <div class="col-sm-7">
      <%= f.text_field :email, :class =>"form-control",:id =>"user_email",:placeholder =>"Email" %>
      <% if @user.errors[:email].any? %>
      <span class="help-block"><%= @user.errors[:email].first %></span>
      <% end %>
    </div>
    <div class="col-sm-2"></div>
  </div>
  <div class="form-group">
    <label for="inputPassword" class="col-sm-3 control-label">Password*</label>
    <div class="col-sm-7">
      <%= f.password_field :password, :class =>"form-control",:id =>"input_password",:placeholder => "Password" %>
      <% if @user.errors[:password].any? %>
      <span class="help-block"><%= @user.errors[:password].first %></span>
      <% end %>
    </div>
    <div class="col-sm-2"></div>
  </div>
  <div class="form-group">
    <label for="inputPassword" class="col-sm-3 control-label">Confirm*</label>
    <div class="col-sm-7">
      <%= f.password_field :password_confirmation, :class =>"form-control",:id =>"input_confirmation_password",:placeholder => "Password confirmation" %>
      <% if @user.errors[:password].any? %>
      <span class="help-block"><%= @user.errors[:password].first %></span>
      <% end %>
    </div>
    <div class="col-sm-2"></div>
  </div>
  <div class="form-group">
    <label for="inputstatus" class="col-sm-3 control-label">Profile Pic</label>
    <div class="col-sm-3">
      <div class="event-title">
        <%= image_tag "Profile-Pic.jpg", :alt=>"image", :class=>"img-thumbnail", :id => "preview" %>
      </div>
    </div>
    <div class="col-sm-3">
      <%= f.file_field :image, :id=>"exampleInputFile" %>
    </div>
    <div class="col-sm-2"></div>
  </div>

</div>
<div class="modal-footer">
  <%= f.submit "Submit", :class =>"btn btn-primary ok-btn-padding" %>
  <!--  <button type="button" class="btn btn-primary ok-btn-padding">OK</button> -->
  <button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
</div>
<% end %>
</div>
</div>
</div>

app/views/time_sheets/_edit.html.erb
<div  id="myCreate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 <div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Edit</h4>
    </div>
    
        <tr>
       <strong><span style="padding-left:20px">Project Name</span></strong>


        <strong><span style="padding-left:40px">Description</span></strong>



       <strong><span style="padding-left:50px">Working Time [In Minutes]</span></strong>
        </tr>
   
      
    <div class="modal-body">
      <%= form_for @time_sheet, remote: :true, html: {:id =>"edit_time_sheet",:class =>"form-horizontal"} do |f| %>
      <div class="form-group alert alert-default alert-dismissible fade in">
        <div class="col-sm-3">
          <%= f.text_field :project_name, :class =>"form-control",:id =>"Name", :placeholder => "project" %> 
        </div>
        <div class="col-sm-5">
          <%= f.text_area :description, :class =>"form-control",:id =>"description", :placeholder => "Task completed", size: "1x1" %> 
        </div>
        <div class="col-sm-2">
          <%= f.number_field :working_time, :class =>"form-control1",:id =>"working_time", :placeholder => "mm" %> 
        </div>
      </div>
      <% end %>
    </div>
    <div class="modal-footer">
      <button id="edit-time-sheet" type="button" class="btn btn-primary" data-dismiss="modal">Update</button>
      <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
       
    </div>
  </div>
</div>
</div>

app/views/time_sheets/_form.html.erb
<%= form_for @time_sheet, remote: :true, html: {:id =>"time_sheet1",:class =>"form-horizontal"} do |f| %>
<div class="form-group alert alert-default alert-dismissible fade in">
  <div class="col-sm-3">
    <%= f.text_field :project_name, :class =>"form-control",:id =>"Name", :placeholder => "project" %> 
  </div>
  <div class="col-sm-5">
    <%= f.text_area :description, :class =>"form-control",:id =>"description", :placeholder => "Task completed", size: "1x1" %> 
  </div>
  <div class="col-sm-2">
    <%= f.number_field :working_time, :class =>"form-control",:id =>"working_time", :placeholder => "mm" %> 
  </div>
  <div class="col-sm-2">
    <%= f.hidden_field :date, :class =>"form-control",:id =>"hiddenDate"%> 
  </div>
  <div class="col-sm-2">
    <%= f.submit "Submit", class: "btn btn-primary" %> 
  </div>
</div>
<% end %>

app/views/time_sheets/_punch_in_modal.html.erb
 <div class="col-sm-6 text-right">
   <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myCreate"> Punch In </button>
   <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myCreate"> Punch Out </button>
   <!-- Punch In Modal -->
   <div class="modal fade" id="myCreate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <h4 class="modal-title" id="myModalLabel">Punch In</h4>
      </div>
      <div class="modal-body"> 
       
       <!-- Model body -->
       <div class="row">
        <div class="col-sm-12">
         <form class="form-horizontal">
          <!--To Add Comments  -->
          <div class="form-group">
           <label for="inputComment" class="col-sm-3 control-label">Comments</label>
           <div class="col-sm-9">
            <textarea class="form-control" id="inputBody" rows="6"></textarea>
           </div>
          </div>
          <div class="modal-footer">
           <button type="button" class="btn btn-primary ok-btn-padding">OK</button>
           <button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
          </div>
         </form>
        </div>
       </div>
       <!-- ./ Moodal body --> 
      </div>
     </div>
    </div>
   </div>
   <!-- ./ Moodal --> 
  </div>

app/views/time_sheets/_schedule.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Daily Schedule View
  </div>
  
  <div class="panel-body">
    <div id="show_form">
       <%= render "form" %>
    </div>
    
    <%= render "time_entries" %>
  </div>    

  <div class="panel-footer text-center"> 
    
    <h3>
      <small>Total Hours :</small>
      <span  class="text-warning" id="hours"><%= @total %></span>
    </h3>
  </div>
</div>

app/views/time_sheets/_time_entries.html.erb
  <table class="table table-condensed">
    <thead>
      <tr>
<strong><span style="padding-left:20px">Date</span></strong>
<strong><span style="padding-left:180px">Project Name</span></strong>
<strong><span style="padding-left:90px">Description</span></strong>
<strong><span style="padding-left:50px">Working Time[In Minutes]</span></strong>


      </tr>
    </thead>
  </table>
  <div id="myDIV">
    <table class="table table-condensed">
      <tbody id="tableData">

        <% @time_sheets.each do |time_sheet| %>
        <tr>
          <td><%= time_sheet.date %></td>
          <td><%= time_sheet.project_name %></td>
          <td><%= truncate(time_sheet.description, length: 15) %></td>
          <td><%= time_sheet.working_time %></td>
          <% if Date.today.strftime("%Y-%m-%d") == @date %>
          <td><%= link_to "Edit", edit_time_sheet_path(time_sheet),:remote => true %></td>

          <% end %>
        </tr>
        <% end %>

      </tbody>

    </table>
  </div>

app/views/time_sheets/_time_entry.html.erb
<tr>
	<td><%= @time_sheet.date %></td>
	<td><%= @time_sheet.project_name %></td>
	<td><%= @time_sheet.description %></td>
	<td><%= @time_sheet.working_time %></td>
	 <td><%= link_to "Edit", edit_time_sheet_path(@time_sheet),:remote => true %></td>
</tr>

app/views/time_sheets/_time_zone.html.erb
<div class="panel panel-primary">
<div class="panel-heading">Time Zone</div>
<div class="panel-body">
<!--Time List -->
  <div class="col-sm-8 col-sm-offset-2">
<form class="form-horizontal">
<div class="form-group">
 <div class="col-sm-10 text-center">
  <input type="text" class="form-control" id="Name" placeholder="2:00">
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10 text-center">
   <input type="text" class="form-control" id="Name" placeholder="2:00">
 </div>
</div>
<div class="form-group ">
 <div class="col-sm-10 text-center">
   <input type="text" class="form-control" id="Name" placeholder="2:00">
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10 text-center">
   <input type="text" class="form-control" id="Name" placeholder="2:00">
 </div>
</div>

</form>
 </div>
</div>
<div class="panel-footer text-center"> <h4>Total Time Spent</h4>
<div class="well well-sm"><h3 class="text-warning">08:00</h3></div>
</div>
</div>
</div>

app/views/time_sheets/create.js.erb
$('#tableData').prepend("<%= escape_javascript(render(:partial=>'time_entry'))%>");
window.location.reload(); 

app/views/time_sheets/edit.js.erb
$('#popup_modal').html("<%= escape_javascript(render(:partial=>'edit')) %>");
$('#popup_modal').modal('show');

app/views/time_sheets/index.html.erb
<!--Content Area-->
<div class="container">
  <div class="row">
    <!--Select Date -->
    <div class="col-sm-6">
      <!--Date -->
      <form role="form" class="form-inline" method="post" id="dateFilter">
        <div class="form-group  form-group-lg">
          <label for="inputDate">Date</label>
          <input type="text" id="timesheetDate" value="<%= @date %>" name="date">
        </div>  
      </form>
    </div>
      <%= render "time_sheets/punch_in_modal" %>
      <hr>
  </div>
  <br>
  <br>
<div class="row">
<div class="col-sm-9">
      <%= render "time_sheets/schedule" %>
      </div>
      <div class="col-sm-3">
      <%= render "time_sheets/time_zone" %>
      </div>
      </div>



  <div id="time_sheet_modal" class="modal fade"></div>
</div>

app/views/time_sheets/new.js.erb
$('#append_form').html("<%= escape_javascript(render(:partial=>'new')) %>");
timesheet_validator()

app/views/timesheets/_schedule.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Daily Schedule View
  </div>
  
  <div class="panel-body">
    <%= render "form" %>
    <%= render "time_entries" %>
  </div>    

  <div class="panel-footer text-center"> 
  <%hours=0,minutes=0
  hours=@total_time/60
  minutes=@total_time%60 %>
    <h3><small>Total Hours :</small> <span class="text-warning"><%= hours %>:<%=minutes %></span></h3>
  </div>
</div>

app/views/timesheets/new.js.erb
$('#append_form').html("<%= escape_javascript(render(:partial=>'new')) %>");
timesheet_validator();

app/views/users/create.js.erb
<% if @success %>
$('#popup_modal').modal('hide');
<% else %>
$('#popup_modal').modal('show');
<% end %>

app/views/users/new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">Sign Up</h4>
    </div>
    <%= form_for :user, url: users_path, method: :post, html: {:class =>"form-horizontal",:id => "sign_in"} do |f| %>
    <div class="modal-body">
      <div class="form-group">
        <label for="Name" class="col-sm-3 control-label">Name</label>
        <div class="col-sm-7">
         <%= f.text_field :name, :class =>"form-control",:id =>"Name", :placeholder => "Name" %>
         <% if @user.errors[:name].any? %>
         <span class="help-block"><%= @user.errors[:name].first %></span>
         <% end %>
       </div>
       <div class="col-sm-2"></div>
     </div>
     <div class="form-group">
      <label for="inputEmail" class="col-sm-3 control-label">Email id</label>
      <div class="col-sm-7">
        <%= f.text_field :email, :class =>"form-control",:id =>"inputEmail",:placeholder =>"Email" %>
        <% if @user.errors[:email].any? %>
        <span class="help-block"><%= @user.errors[:email].first %></span>
        <% end %>
      </div>
      <div class="col-sm-2"></div>
    </div>
    <div class="form-group">
      <label for="inputPassword" class="col-sm-3 control-label">Password</label>
      <div class="col-sm-7">
        <%= f.password_field :password, :class =>"form-control",:id =>"inputPassword",:placeholder => "Password" %>
        <% if @user.errors[:password].any? %>
        <span class="help-block"><%= @user.errors[:password].first %></span>
        <% end %>
      </div>
      <div class="col-sm-2"></div>
    </div>
    <div class="form-group">
      <label for="inputPassword" class="col-sm-3 control-label">Confirm</label>
      <div class="col-sm-7">
        <%= f.password_field :password_confirmation, :class =>"form-control",:id =>"inputPassword",:placeholder => "Password confirmation" %>
        <% if @user.errors[:password].any? %>
        <span class="help-block"><%= @user.errors[:password].first %></span>
        <% end %>
      </div>
      <div class="col-sm-2"></div>
    </div>
    
  </div>
  <div class="modal-footer">
    <%= f.submit "Submit", :class =>"btn btn-primary ok-btn-padding" %>
    <!--  <button type="button" class="btn btn-primary ok-btn-padding">OK</button> -->
    <button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
  </div>
  <% end %>
</div>
</div>
</div>